language: objective-c
osx_image: xcode7.3
xcode_project: MedHelp.xcodeproj
xcode_scheme: MedHelp
xcode_sdk: iphonesimulator9.3

script:
    - xcodebuild test -project MedHelp.xcodeproj -scheme MedHelp -sdk iphonesimulator9.3 -destination 'platform=iOS Simulator,name=iPhone 6,OS=9.3'
